import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author raphael.ccosta1
 */
public class CadastroJogador extends javax.swing.JFrame {

    /**
     * Creates new form CadastroJogador
     */
    public CadastroJogador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        camisaJog = new javax.swing.JTextField();
        nomeJog = new javax.swing.JTextField();
        apelidoJog = new javax.swing.JTextField();
        nacionalidade = new javax.swing.JTextField();
        btnJogador = new javax.swing.JButton();
        posicaoJog = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Registrar Jogador");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 10, 220, 60);

        jLabel2.setText("n° camisa:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 220, 60, 20);

        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 100, 60, 20);

        jLabel4.setText("Apelido:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 140, 60, 20);

        jLabel5.setText("Nacionalidade:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 180, 90, 20);

        jLabel6.setText("Posição:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 260, 60, 20);
        getContentPane().add(camisaJog);
        camisaJog.setBounds(220, 210, 120, 30);
        getContentPane().add(nomeJog);
        nomeJog.setBounds(220, 90, 120, 30);
        getContentPane().add(apelidoJog);
        apelidoJog.setBounds(220, 130, 120, 30);
        getContentPane().add(nacionalidade);
        nacionalidade.setBounds(220, 170, 120, 30);

        btnJogador.setText("Ok");
        btnJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogadorActionPerformed(evt);
            }
        });
        getContentPane().add(btnJogador);
        btnJogador.setBounds(100, 320, 240, 40);

        posicaoJog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ATA", "MEI", "ZAG", "LD", "LF", "PD" }));
        getContentPane().add(posicaoJog);
        posicaoJog.setBounds(220, 250, 120, 30);

        setSize(new java.awt.Dimension(462, 441));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogadorActionPerformed
        
        String nome, apelido,nac,camisa,posicao;
        
        int id = (int)Math.floor(Math.random()*500);
        
        nome = nomeJog.getText();
        apelido = apelidoJog.getText();
        nac = nacionalidade.getText();
        camisa = camisaJog.getText();
        posicao = posicaoJog.getSelectedItem().toString();
        
        
        try {
            // CONECTAR AO BANCO
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3306/championsleague", "root", "");
            
            PreparedStatement st = conectar.prepareStatement("INSERT INTO jogador VALUES(?,?,?,?,?,?)");
            
            st.setString(1, nome);
            st.setString(2, apelido);
            st.setString(3, nac);
            st.setString(4, camisa);        
            st.setString(5, posicao);
            st.setInt(6, id);
            
            st.executeUpdate();
            JOptionPane.showMessageDialog(null, "Jogador Cadastrado");
            
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
        
        
        
    }//GEN-LAST:event_btnJogadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroJogador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apelidoJog;
    private javax.swing.JButton btnJogador;
    private javax.swing.JTextField camisaJog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nacionalidade;
    private javax.swing.JTextField nomeJog;
    private javax.swing.JComboBox<String> posicaoJog;
    // End of variables declaration//GEN-END:variables
}
